--- @class LuaPath 
--- @field forced boolean 
--- @field forcedDest nil|Loc 
--- @field forcedMovementTotalDistance number 
--- @field collisionSpeed number 
--- @field mount any 
--- @field waterSteps any 
--- @field difficultSteps any 
--- @field squeezeSteps any 
--- @field numDiagonals any 
--- @field cost any 
--- @field numSteps any 
--- @field destinationPosition any 
--- @field destination any 
--- @field origin any 
LuaPath = {}
